# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odigos < Formula
  desc "Odigos CLI Utility"
  homepage "https://odigos.io"
  version "1.15.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odigos-io/odigos/releases/download/v1.15.0-rc1/cli_1.15.0-rc1_darwin_amd64.tar.gz"
      sha256 "94e1a120d7cc38b86bfe9b226b940459777133a74df79fc2632175ea8e6c423c"

      def install
        bin.install "odigos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odigos-io/odigos/releases/download/v1.15.0-rc1/cli_1.15.0-rc1_darwin_arm64.tar.gz"
      sha256 "156499c3f649e031c65490864c562b00c207aa2372f8b896a649f96beb3931f2"

      def install
        bin.install "odigos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/odigos-io/odigos/releases/download/v1.15.0-rc1/cli_1.15.0-rc1_linux_amd64.tar.gz"
      sha256 "93cac22113ae4fdeea144b3a8aec520f39e8313126dd0ccd402c82267ce68a01"
      def install
        bin.install "odigos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odigos-io/odigos/releases/download/v1.15.0-rc1/cli_1.15.0-rc1_linux_arm64.tar.gz"
      sha256 "85d76370534bdef04a96cc0f76a03ad59d4ed3623caf62b999ba49dd6b71700c"
      def install
        bin.install "odigos"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing Odigos CLI! Please run `odigos install` to install Odigos in your Kubernetes cluster.
    EOS
  end
end
