# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odigos < Formula
  desc "Odigos CLI Utility"
  homepage "https://odigos.io"
  version "1.27.0-rc0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odigos-io/odigos/releases/download/v1.27.0-rc0/cli_1.27.0-rc0_darwin_amd64.tar.gz"
      sha256 "b06640832bb22e7940200ffa2ceaf27ded9e27367fe1e82da9551736fca6a4e2"

      define_method(:install) do
        bin.install "odigos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odigos-io/odigos/releases/download/v1.27.0-rc0/cli_1.27.0-rc0_darwin_arm64.tar.gz"
      sha256 "fffdf8f9662b0a1eea8c9a5f86746cb7e3dbdea85030f096a0b228b1182141fb"

      define_method(:install) do
        bin.install "odigos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/odigos-io/odigos/releases/download/v1.27.0-rc0/cli_1.27.0-rc0_linux_amd64.tar.gz"
      sha256 "2b453129fb2eb5b52820135f2d3a259c1c57f5dcde576838ce9d63ee2aab1744"
      define_method(:install) do
        bin.install "odigos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odigos-io/odigos/releases/download/v1.27.0-rc0/cli_1.27.0-rc0_linux_arm64.tar.gz"
      sha256 "9683cd91776ed3e44d1087245eeb967b4ebaa3de61a57c91b27080f553bf22a6"
      define_method(:install) do
        bin.install "odigos"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing Odigos CLI! Please run `odigos install` to install Odigos in your Kubernetes cluster.
    EOS
  end
end
