# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Odigos < Formula
  desc "Odigos CLI Utility"
  homepage "https://odigos.io"
  version "1.24.0-rc0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odigos-io/odigos/releases/download/v1.24.0-rc0/cli_1.24.0-rc0_darwin_amd64.tar.gz"
      sha256 "1694e1898983cd622207609b5735acdecc8365118d40f062a08a304e806fa33c"

      define_method(:install) do
        bin.install "odigos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odigos-io/odigos/releases/download/v1.24.0-rc0/cli_1.24.0-rc0_darwin_arm64.tar.gz"
      sha256 "b78a35029b81fa4bbdc7e0b002d69c09d8510d133be0ba3a00972611229f9a11"

      define_method(:install) do
        bin.install "odigos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/odigos-io/odigos/releases/download/v1.24.0-rc0/cli_1.24.0-rc0_linux_amd64.tar.gz"
      sha256 "822c54d2b1fc7deedd21511fadfe91a22f2760c6e23c634abb4997dae4973353"
      define_method(:install) do
        bin.install "odigos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odigos-io/odigos/releases/download/v1.24.0-rc0/cli_1.24.0-rc0_linux_arm64.tar.gz"
      sha256 "967140884540c741a45b8f8ee73527798cc0e16ab16d075eace5e2635fba8b21"
      define_method(:install) do
        bin.install "odigos"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing Odigos CLI! Please run `odigos install` to install Odigos in your Kubernetes cluster.
    EOS
  end
end
